name: mainplate
version: 0.0.1.0
synopsis: TODO
description: TODO
maintainer: Peter Trško <peter.trsko@gmail.com>
license: BSD3
github: trskop/mainplate
category: System, Text

extra-source-files:
  - ChangeLog.md
  - README.md

ghc-options: -Wall

dependencies:
  - base >=4.7 && <5
  - host-and-port
  - network
  - optparse-applicative
  - verbosity

library:
  source-dirs: src
  exposed-modules:
    - Main.Run
    - Options.Applicative.Standard.Options

# tests:
  # spec:
    # cpp-options: -DTEST
    # main: Spec.hs
    # source-dirs:
      # - test
      # - src
    # dependencies:
      # - hspec == 2.*
      # - QuickCheck
      # - temporary
      # - mockery >= 0.3
      # - interpolate
      # - aeson-qq
